Vagrant.configure("2") do |config|
  # centos8
  config.vm.define "centos8" do |centos8|
    centos8.vm.box = "geerlingguy/centos8"
    centos8.vm.network "private_network", ip: "192.168.221.10"
    centos8.vm.hostname = "centos8"
    centos8.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "1"]
    end
  end

  # centos7
  config.vm.define "centos7" do |centos7|
    centos7.vm.box = "geerlingguy/centos7"
    centos7.vm.network "private_network", ip: "192.168.221.11"
    centos7.vm.hostname = "centos7"
    centos7.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "1"]
    end
  end

  # ubuntu bionic
  config.vm.define "bionic" do |bionic|
    bionic.vm.box = "ubuntu/bionic64"
    bionic.vm.network "private_network", ip: "192.168.221.12"
    bionic.vm.hostname = "bionic"
    bionic.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "1"]
    end
  end
end
