version: '3'

services:
  node:
    image: xthor/helloworld
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - "8085:8080"
    deploy:
      labels:
        - "traefik.port=8085"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=PathPrefixStrip:/hello"
    networks:
      - default
      - traefik-net

networks:
  traefik-net:
    external: True
