version: '3'

services:
  whoami:
    image: emilevauge/whoami
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=PathPrefixStrip:/whoami"
    networks:
      - default
      - traefik-net

networks:
  traefik-net:
    external: True
