#!/bin/bash

# meant to be run via systemd on a vbox minion
# an easier way to deploy since salt-cloud doesn't work

newHostName=$(VBoxControl --nologo guestproperty get GuestName | awk '{ print $2 }')

# make sure the result isn't zero length (indicating VBoxControl doesn't work), or "value" (not set)
if [ ${#newHostName} -eq 0 ]; then
  echo "vbox guest property not set - exiting."
  exit 255
elif [ "${newHostName}" == "value" ]; then
  echo "vbox guest property not set - exiting."
  exit 255
fi

# set the hostname
hostnamectl set-hostname ${newHostName}.lab

# statically set the hostname in Salt
echo ${newHostName}.lab > /etc/salt/minion_id

# point the minion at the right master
echo "master: 10.187.88.10" | tee /etc/salt/minion

# stupid Ubuntu and netplan...
test -f /etc/machine-id && echo > /etc/machine-id
netif=$(ip route | grep default | awk '{ print $5 }')
echo "auto ${netif}" > /etc/network/interfaces && echo "iface ${netif} inet dhcp" >> /etc/network/interfaces
if [ $? -eq 0 ]; then
    apt -y install ifupdown && apt -y purge netplan.io && rm -vfr /usr/share/netplan /etc/netplan
    if [ $? -ne 0 ]; then
        echo "Error removing netplan"
        exit 255
    fi
else
    echo "Error writing /etc/network/interfaces"
    exit 255
fi

# start Salt minion next boot
systemctl enable salt-minion

# get rid of the evidence
systemctl disable minion-setup
rm /etc/systemd/system/minion-setup.service
systemctl daemon-reload

# reboot after burying the body
(sleep 5; reboot &)
rm ${0}

# fin
exit 0
